Source = https://www.machinelearningplus.com/python/101-numpy-exercises-python/

# 1\. Import numpy as np and see the version
Difficulty Level: L1<br>

> Q. Import numpy as np and print the version number.

## Solution

> My solution

In [24]:
import numpy as np

> Solution

In [ ]:
import numpy as np
print(np.__version__)

1.21.6

# 2\. How to create a 1D array?
Difficulty Level: L1<br>

Q. Create a 1D array of numbers from 0 to 9

> Desired output:
    #> array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Solution

> My solution

In [25]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

> Solution

In [26]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# 3\. How to create a boolean array?
Difficulty Level: L1<br>

Q. Create a 3×3 numpy array of all True

## Solution

> My solution

In [ ]:
arr = np.full((3,3), True)
arr

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

> Solution

In [ ]:
np.full((3, 3), True, dtype=bool)

# Alternate method
np.ones((3,3), dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

# 4\. How to extract items that satisfy a given condition from 1D array?
Difficulty Level: L1<br>

Q. Extract all odd numbers from `arr`<br>

> input:<br>

    arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

> Desired output:<br>

    #> array([1, 3, 5, 7, 9])

## Solution

> My solution

In [ ]:
arr = np.array([0,1,2,3,4,5,6,7,8,9])

arr[(arr%2) == 1]

array([1, 3, 5, 7, 9])

> Solution

In [ ]:
arr[arr % 2 == 1]

# 5\. How to replace items that satisfy a condition with another value in numpy array?
Difficulty Level: L1<br>

Q. Replace all odd numbers in arr with -1

> Input:

    arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

> Desired Output:

    #>  array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

## Solution

> My solution

In [ ]:
arr = np.array([0,1,2,3,4,5,6,7,8,9])

arr[arr%2 == 1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

> Solution

In [13]:
arr[arr % 2 == 1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

# 6\. How to replace items that satisfy a condition without affecting the original array?
Difficulty Level: L2<br>

Q. Replace all odd numbers in arr with -1 without changing `arr`

> input:

    arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

> Desired Output:

    out
    #>  array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])
    arr
    #>  array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Solution

> My solution

In [19]:
arr = np.array([0,1,2,3,4,5,6,7,8,9])

out = arr.copy()
out[out%2 == 1] = -1

In [20]:
out

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [21]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

> Solution

In [22]:
arr = np.arange(10)
out = np.where(arr % 2 == 1, -1, arr)
print(arr)
out

[0 1 2 3 4 5 6 7 8 9]

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

> \# Study Point
- ***np.where()*** 함수는 'X if Y else Z'와 같은 삼항식 기능의 함수이다.
- `np.where(X, Y, Z)` 의 형식으로 사용한다.
    - X : 참, 거짓의 자료 및 조건을 의미
    - Y : X의 조건이 참일 경우 출력
    - Z : X의 조건이 거짓일 경우 출력

In [23]:
# Example
arr1 = [1.1, 1.2, 1.3, 1.4, 1.5]
arr2 = [2.1, 2.2, 2.3, 2.4, 2.5]

arr = [True, False, True, False, True]

result = np.where(arr, arr1, arr2)
result

array([1.1, 2.2, 1.3, 2.4, 1.5])

# 7\. How to reshape an array?
Difficulty Level: L1<br>

Q. Convert a 1D array to a 2D array with 2 rows

> input:

    np.arange(10)

    #> array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

> Desired Output:

    #> array([[0, 1, 2, 3, 4],
    #>        [5, 6, 7, 8, 9]])

## Solution

> My solution

In [29]:
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

> Solution

In [ ]:
arr = np.arange(10)
arr.reshape(2, -1)  # Setting to -1 automatically decides the number of cols
#> array([[0, 1, 2, 3, 4],
#>        [5, 6, 7, 8, 9]])

> \# Study Point
- `reshape()` 에서 열(or행)을 정할 때 ***-1***을 입력하면, 자동으로 정해진 행(or열)의 숫자에 맞는 열(or행)을 맞춰준다.

In [32]:
# Example
arr = np.arange(20)

arr1 = arr.reshape(5,-1)
arr2 = arr.reshape(-1, 10)

In [33]:
arr1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [34]:
arr2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

# 8\. How to stack two arrays vertically?
Difficulty Level: L2<br>

Q. Stack arrays a and b vertically

> input:

    a = np.arange(10).reshape(2,-1)
    b = np.repeat(1, 10).reshape(2,-1)

> Desired Output:

    #> array([[0, 1, 2, 3, 4],
    #>        [5, 6, 7, 8, 9],
    #>        [1, 1, 1, 1, 1],
    #>        [1, 1, 1, 1, 1]])

## Solution

> My solution

In [54]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
np.append(a,b, axis=0)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

> Solution

In [ ]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

# Answers
# Method 1:
np.concatenate([a, b], axis=0)

# Method 2:
np.vstack([a, b])

# Method 3:
np.r_[a, b]
#> array([[0, 1, 2, 3, 4],
#>        [5, 6, 7, 8, 9],
#>        [1, 1, 1, 1, 1],
#>        [1, 1, 1, 1, 1]])

> \# Study Point
- array는 numpy의 append 메소드를 이용하여 추가할 수 있다.
- `np.append(X, Y)` 의 형식을 사용한다.
    - X : 값이 추가되는 배열
    - Y : 값을 추가할 배열
    - 추가하는 값은 같은 차원의 배열에 추가된다.
- 다른 차원의 배열로 값을 추가하는 경우는, 괄호의 마지막에 옵션으로 `axis=0` 을 입력하여 차원을 지정해준다.

In [83]:
# Example
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[1,3,5],[5, 7,9]])

arr3 = np.append(arr1, arr2)
arr4 = np.append(arr1, arr2, axis=0)

print(arr3)
print()

print(arr4)

[1 2 3 4 5 6 1 3 5 5 7 9]

[[1 2 3]
 [4 5 6]
 [1 3 5]
 [5 7 9]]